services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: poc-bumblebee
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    ports:
      - "8001:8001"
    networks:
      - errekaese_app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: poc-bumblebee-frontend
    ports:
      - "3000:8080"
    depends_on:
      - backend
    networks:
      - errekaese_app-network
    restart: unless-stopped

networks:
  errekaese_app-network:
    external: true